genetic_algorithm:
  num_steps_ga: 20
  number_population: 8
  mutation_rate: 0.3
  elitism_ratio : 0.2
  cross_over_ratio: 0.7
  max_llm_attempts: 3

llm:
  backend: "openai" # openai or hf
  openai_args:
    base_url: "https://api.deepseek.com"
  hf_args:
    provider: "together"
  model_name: "deepseek-reasoner" # "o4-mini-2025-04-16"  "deepseek-ai/DeepSeek-V3" "deepseek-ai/DeepSeek-R1" "Qwen/Qwen2-72B-Instruct"

solver:
  time_limit: 10 # Time Limit for solver to solve
  solver_name: "gurobi_persistent"  # gurobi, appsi_highs, glpk, gurobi_persistent
  max_time_out: 1000 # Time Limit to allow the solver to solve the inital solve for each instance
  apply_lazy: true # Apply lazy constraints to the solver
  lazy_value: 1 # Value of the lazy constraints
  pool_solutions : 2

